services:
  n8n:
    container_name: n8n
    build: .
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_HOST=n8n_postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_SCHEMA=public
      - DB_POSTGRESDB_PASSWORD=postgres
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n-workshop-network

  postgres:
    container_name: n8n_postgres
    image: postgres:latest
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql:/var/lib/postgresql/data"
    networks:
      - n8n-workshop-network

networks:
  n8n-workshop-network:
    driver: bridge

volumes:
  n8n_data:
